import type { MeshMember } from "./directory";

/**
 * Renders the Headscale access policy from Kimono VPN membership.
 *
 * Tailscale-style policy is default-deny: a pair that no rule names cannot
 * connect. That is what makes each member's mesh isolated without Kimono
 * writing a single deny rule — a member reaches their own devices because one
 * rule says so, and reaches nobody else's until an invitation adds another.
 */
export function renderMeshPolicy(members: Record<string, MeshMember>): string {
  const names = Object.keys(members).sort();

  const acls: Array<{ comment: string; src: string; dst: string }> = [
    { comment: "Kimono's own service identities, administered by the appliance.", src: "tag:kimono-admin", dst: "tag:kimono-node:*" },
  ];

  for (const name of names) {
    acls.push({ comment: `${name} reaches their own devices.`, src: `${name}@`, dst: `${name}@:*` });
  }
  for (const name of names) {
    for (const guest of [...members[name].guests].sort()) {
      /* Only a guest who still holds access can be named, or the policy would
         reference a principal Headscale does not know and refuse to load. */
      if (!members[guest]) continue;
      acls.push({ comment: `${guest} was invited into ${name}'s mesh.`, src: `${guest}@`, dst: `${name}@:*` });
    }
  }

  const lines = [
    "// Generated by Kimono. Do not edit; change Kimono VPN in the Portal.",
    "{",
    "  // Reserved policy principal. Kimono never creates this as a login; trusted",
    "  // administrator tags are assigned only by server-minted enrollment keys.",
    '  "groups": {',
    '    "group:kimono-control-plane": ["kimono-control-plane@"],',
    "  },",
    '  "tagOwners": {',
    '    "tag:kimono-node": ["tag:kimono-admin"],',
    '    "tag:kimono-admin": ["group:kimono-control-plane"],',
    "  },",
    '  "acls": [',
  ];
  for (const acl of acls) {
    lines.push(
      `    // ${acl.comment}`,
      "    {",
      '      "action": "accept",',
      `      "src": [${JSON.stringify(acl.src)}],`,
      `      "dst": [${JSON.stringify(acl.dst)}],`,
      "    },",
    );
  }
  lines.push("  ],", "}", "");
  return lines.join("\n");
}
