import {
  KIMONO_APP_CONTRACT_VERSION,
  type KimonoAppManifest,
  type KimonoProfile,
} from "@kimono/app-sdk";

export const currentProfile: KimonoProfile = {
  id: "usr_owner",
  username: "kimo",
  displayName: "Kimo",
  email: "kimo@kimono.local",
  role: "owner",
};

export const applications: KimonoAppManifest[] = [
  {
    id: "movies",
    name: "Movies",
    shortDescription: "Watch your household library.",
    longDescription: "Films, shows, watchlists, and continuing playback across the household.",
    href: "#",
    kind: "fork",
    presentation: "standalone",
    status: "online",
    accent: "#e65f3c",
    category: "media",
    icon: "play",
    brand: { colors: ["#f47a45", "#b73555", "#ffd2ad"] },
    enabled: true,
    visibleTo: ["owner", "admin", "member", "guest"],
    contractVersion: KIMONO_APP_CONTRACT_VERSION,
  },
  {
    id: "photos",
    name: "Photos",
    shortDescription: "Keep your shared memories close.",
    longDescription: "Private photo backup, albums, sharing, and household memories.",
    href: "#",
    kind: "connected",
    presentation: "standalone",
    status: "online",
    accent: "#477b68",
    category: "media",
    icon: "image",
    brand: { colors: ["#55a08d", "#496ca8", "#d9f0e7"] },
    enabled: true,
    visibleTo: ["owner", "admin", "member"],
    contractVersion: KIMONO_APP_CONTRACT_VERSION,
  },
  {
    id: "drive",
    name: "Drive",
    shortDescription: "Files without the filing cabinet.",
    longDescription: "A calm home for documents, uploads, and files shared between Kimono apps.",
    href: "#",
    kind: "native",
    presentation: "standalone",
    status: "setup",
    accent: "#527eb4",
    category: "files",
    icon: "file",
    brand: { colors: ["#5c8fc1", "#7659a6", "#d7e7f5"] },
    enabled: true,
    visibleTo: ["owner", "admin", "member"],
    contractVersion: KIMONO_APP_CONTRACT_VERSION,
  },
  {
    id: "tools",
    name: "Tools",
    shortDescription: "Small utilities, without sketchy websites.",
    longDescription: "Household PDF, image, archive, and conversion tools running locally.",
    href: "#",
    kind: "native",
    presentation: "standalone",
    status: "setup",
    accent: "#a06b38",
    category: "tools",
    icon: "tool",
    brand: { colors: ["#d29a43", "#a54e43", "#f5dfb5"] },
    enabled: true,
    visibleTo: ["owner", "admin", "member"],
    contractVersion: KIMONO_APP_CONTRACT_VERSION,
  },
];

export const householdMembers = [
  { name: "Kimo", handle: "@kimo", role: "Owner", status: "Active", apps: 4 },
  { name: "Household member", handle: "@member", role: "Member", status: "Invited", apps: 3 },
];
